---
abstract: 'Verify and Optimise CGI Output'
author:
  - 'Nigel Horne <njh@bandsman.co.uk>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.142690'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CGI-Buffer
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Info: '0.42'
  CSS::Packer: '0'
  Carp: '0'
  Compress::Zlib: '0'
  DateTime: '0'
  Digest::MD5: '0'
  Encode: '0'
  File::Spec: '0'
  HTML::Lint: '0'
  HTML::Packer: '1'
  HTTP::Date: '0'
  IO::CaptureOutput: '0'
  IO::String: '0'
  JavaScript::Packer: '1.006003'
  Storable: '0'
  Test::Most: '0'
  Test::TempDir: '0'
  Time::localtime: '0'
  perl: '5.006002'
resources:
  repository: git://github.com/nigelhorne/CGI-Buffer.git
version: '0.73'
