---
abstract: 'Optimise the output of a CGI Program'
author:
  - 'Nigel Horne <njh@bandsman.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Buffer
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Info: 0.11
  CSS::Packer: 0
  Carp: 0
  Compress::Zlib: 0
  DateTime: 0
  Digest::MD5: 0
  Encode: 0
  HTML::Packer: 1
  HTTP::Date: 0
  IO::CaptureOutput: 0
  IO::String: 0
  JavaScript::Packer: 1.006003
  Test::Kwalitee: 0
  Test::More: 0.82
version: 0.46
